# Configuration file for MegaLinter
---

APPLY_FIXES: none

ENABLE:
  - ACTION
  - BASH
  - DOCKERFILE
  - GROOVY
  - JSON
  - MARKDOWN
  - YAML

ENABLE_LINTERS:
  - PYTHON_RUFF
  - PYTHON_ISORT

DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

FILTER_REGEX_EXCLUDE: (Slides.*/)

PRINT_ALPACA: false
