# Configuration file for MegaLinter
---
APPLY_FIXES: none

ENABLE:
  - ACTION
  - BASH
  - DOCKERFILE
  - GROOVY
  - JSON
  - MARKDOWN
  - YAML

ENABLE_LINTERS:
  - PYTHON_RUFF

DISABLE_LINTERS:
  - BASH_SHFMT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

FILTER_REGEX_EXCLUDE: (Slides.*/|renv/)

PRINT_ALPACA: false

BASH_SHFMT_ARGUMENTS: "-i 4"
