name: Selenium Tests

on:
  workflow_dispatch:

permissions:
  variables: write

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        working-directory: Enrollment
        run: |
          docker compose build
          docker compose pull

      - name: Run Selenium tests
        working-directory: Enrollment
        timeout-minutes: 2
        run: |
          docker compose up --abort-on-container-exit --exit-code-from tester

      - name: Read result from file
        id: read_result
        working-directory: Enrollment
        run: |
          if [ -f ./output/result.txt ]; then
            echo "NEW_SEATS=$(cat ./output/result.txt)" >> "$GITHUB_ENV"
          else
            echo "Result file not found!"
            exit 1
          fi

      - name: Confirm unchanged
        if: ${{ vars.SEATS_LEFT == env.NEW_SEATS }}
        run: |
          echo "Unchanged: ${{ vars.SEATS_LEFT }} / $NEW_SEATS"

      - name: Confirm changed
        if: ${{ vars.SEATS_LEFT != env.NEW_SEATS }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$OWNER/$REPO/actions/variables/SEATS_LEFT" \
            -f "name=SEATS_LEFT" -f "value=$NEW_SEATS"

      - name: Tear down Docker Compose
        if: always()
        working-directory: Enrollment
        run: |
          docker compose down
